apiVersion: v1
kind: Service
metadata:
  name: ticketing-service
  labels:
    app: ticketing
spec:
  type: NodePort
  selector:
    app: ticketing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
